### ISSUE TITLE
底部的成交量画出来好像不对啊

### ISSUE THREAD

**Issue by 329463417** [MarcWeigert/GGCharts#15]
![7557286fafdb73230342e3c3cb9baa4b](https://user-images.githubusercontent.com/13717029/35210840-bff6bb2a-ff8e-11e7-99b2-ac98b7e7eb4b.png)
![320444829f0ae86dd3d1d64084bf75ea](https://user-images.githubusercontent.com/13717029/35210842-c0278f7a-ff8e-11e7-880d-ba1101c72e7f.png)

**Comment by 329463417** [comment]
是成交量比较低的原因么

**Comment by MarcWeigert** [comment]
这成交量很明显不一致啊。建议你输出日志对一下。

**Comment by JhonnyRtd** [comment]
这个极值怎么弄的。。
