### ISSUE TITLE
这样确定不会死锁？ 

### ISSUE THREAD

**Issue by zhouzhuhao** [MarcWeigert/GGCharts#5]
void runMainThreadWithBlock(Function block)
{
    if (![NSThread isMainThread]) {
        dispatch_sync(dispatch_get_main_queue(), ^{
            block();
        });
    }
    else {
        block();
    }
}

**Comment by MarcWeigert** [comment]
不会死锁，因为判断了当前线程是否为主线程。不是主线程才会同步加到主线程中。

**Comment by zhouzhuhao** [comment]
有一个疑问，别的地方执行：dispatch_async(dispatch_get_main_queue(), ^{
});
