### ISSUE TITLE
K线图在数据少的情况下崩溃

### ISSUE THREAD

**Issue by 329463417** [MarcWeigert/GGCharts#7]
K线图在K线数据少，比如新股，会出现内存瞬间暴涨崩溃的情况，我看了很久没找到原因，作者能自己看看么

**Comment by MarcWeigert** [comment]
应该是被除数为0的情况没有判断。我这边暂时没有时间排查，你可以检查下最高价、最低价、开盘、收盘 是否为0

**Comment by 329463417** [comment]
不是数据为0 造成的，是内存暴增，直接造成的闪退

**Comment by 329463417** [comment]
崩溃日志：Message from debugger: Terminated due to memory issue

**Comment by MarcWeigert** [comment]
这个原因应该就是被除数为0的情况。 你模拟一下  5/0  试一试。最好提供demo，让我完善下k线。
