### ISSUE TITLE
K线图均线在左测显示不完整

### ISSUE THREAD

**Issue by 329463417** [MarcWeigert/GGCharts#8]
K线图均线在左测显示不完整，出现断的情况

**Comment by MarcWeigert** [comment]
请给图。或者具体事例。

**Comment by 329463417** [comment]
![b2967dd9-df09-43b2-b035-c07969ca6d2c](https://user-images.githubusercontent.com/13717029/34354741-622ae0e4-ea6b-11e7-8241-5f0d4f4def66.png)

**Comment by MarcWeigert** [comment]
这个是5，10，20，40 日均线。因为前面数据不足（5，10，20，40）根，所以是断的。
